language: php

php:
  - 5.5
  - 5.6

script:
  - composer install
  - composer require codeclimate/php-test-reporter
  - phpunit

after_success:
  - CODECLIMATE_REPO_TOKEN=00cf98675c9bc3572873a4748cbf14615e3b5a0c8ec7143a734cea40efac3e34 ./vendor/bin/test-reporter
