language: php

php:
  - 5.5
  - 5.6

install:
  - composer require satooshi/php-coveralls

before_script:

script:
  - mkdir -p build/logs
  - phpunit --bootstrap src/autoload.php --coverage-clover build/logs/clover.xml

after_success:
  - php vendor/bin/coveralls -v'

notifications:
  slack: cgtag:vMfPenstmAFcQeZnYNVp4H6Y