language: php

php:
  - 5.5
  - 5.6

script:
  - composer install
  - mkdir -p build/logs
  - phpunit --bootstrap src/bootstrap.php --coverage-clover build/logs/clover.xml

after_success:
  - php vendor/bin/coveralls -v

notifications:
  slack: cgtag:vMfPenstmAFcQeZnYNVp4H6Y