language: php

php:
  - 5.5
  - 5.6

script:
  - composer install
  - composer require satooshi/php-coveralls
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - php vendor/bin/coveralls -v

notifications:
  slack: cgtag:vMfPenstmAFcQeZnYNVp4H6Y